### ISSUE TITLE
typo for route in README

### ISSUE THREAD

**Issue by discdiver** [ManuCastrillonM/disney-api#11]
```
Get one character
Get the details about one character using the character/:id endpoint.
```

*characters* should be changed to *characters*

```
Get the details about one character using the characters/:id endpoint.
```

**Comment by ManuCastrillonM** [comment]
Hi @discdiver 👋 
Thanks for reporting this issue, typo fixed on https://github.com/ManuCastrillonM/disneyapi.dev/commit/f0d7f58837e3423d59144ca62c4767e97284eef2 ✅
