### ISSUE TITLE
Case insensitive filter 

### ISSUE THREAD

**Issue by mathieutu** [ManuCastrillonM/disney-api#19]
Hi! 
Thanks for this great API.
FYI, I'm a teacher and using it with my students as a fun api to fetch and to play with.

It could be cool to be able to filter without wondering about the case. 
ex: `https://api.disneyapi.dev/character?name=Abu` is returning the results, but `https://api.disneyapi.dev/character?name=abu` is not.

WDYT?

Thanks.

**Comment by ManuCastrillonM** [comment]
Hi Mathieu,
Thank you for using the API with your students and for contributing this improvement idea ✨ 

✅ I just added the fix so it should be working now. Please let me know if it looks ok to you
