### ISSUE TITLE
Characters filtering GraphQL

### ISSUE THREAD

**Issue by nachocapodanno** [ManuCastrillonM/disney-api#22]
I'm using your API (its awesome 🚀) and I'd like to have a filtering for characters by films or other fields for GraphQL. I've already got this code (I create a filter input for characters query). Could I contribute to this project?

Thanks in advance & congrats for this again! 👋
https://www.loom.com/share/476d287c30fa44c1bcb55ff5abe268a0

**Comment by ManuCastrillonM** [comment]
Hi Nacho,
Thank you for using the API!
That's a great idea, and I would love to see your contribution.

**Comment by nachocapodanno** [comment]
Hi Manu! I created a PR. Thanks!!

**Comment by ManuCastrillonM** [comment]
Awesome! Thank you for your contribution 🌟

![giphy](https://user-images.githubusercontent.com/10585946/218224066-85d7cf32-1ee7-4734-b78e-4fd9930e06fb.gif)

I'll go ahead and close this issue.
