### ISSUE TITLE
Api doesn't support itemsPerPage?

### ISSUE THREAD

**Issue by oalagial** [ManuCastrillonM/disney-api#25]
I am trying to fetch data like "https://api.disneyapi.dev/characters?page=1&**itemsPerPage=1000**". or something similar.
Api doesn't support dynamic PAGE_SIZE? 

Thank you very much.

**Comment by ManuCastrillonM** [comment]
Hi @oalagial 
Thanks for the suggestion; I just added support for dynamic page size.

Example of usage:
https://api.disneyapi.dev/characters?page=2&pageSize=60

I hope this helps you solve your use case.
