### ISSUE TITLE
Filtering not working

### ISSUE THREAD

**Issue by lntaopoulos** [ManuCastrillonM/disney-api#28]
Hi there! 

Thank you for implementing this really nice open API!

I'm afraid I found an issue with filtering functionality by name and wanted to report it.

As you mention in the docs, the following should return a single result but returns all results instead.
`https://api.disneyapi.dev/character?name=Mickey%20Mouse`

Could you investigate this please?

**Comment by ManuCastrillonM** [comment]
Hi folks!
Thank you for reporting this issue 🙌 It was a bug and should be working now.
Please let me know if it works for you.

**Comment by lntaopoulos** [comment]
Thank you very much for checking this! 

Filtering seems to be working now for names that I know that I will get a result back (let's say 'Mickey'). If I try to search something that is not there though, the response is incomplete. I was expecting to get an empty `data` array but now I get only info property back from back end. Is this indented?

![image](https://user-images.githubusercontent.com/132107863/236707225-73916f21-3079-401e-be89-ac2c99ca90aa.png)

**Comment by ManuCastrillonM** [comment]
Thanks for the feedback. I just added the data field even when no characters are found.
